export const PALETTE: Record<string, string> = {
  ' ': 'transparent',
  A: '#14162a',
  B: '#2a2d4c',
  C: '#122408',
  D: '#1f3e18',
  E: '#2e5a23',
  F: '#468039',
  G: '#62a149',
  H: '#8cc768',
  S: '#343857',
  T: '#4b4f71',
  U: '#757a9c',
  V: '#989cc0',
  W: '#b57a2a',
  X: '#d88d24',
  Y: '#f3a22c',
  Z: '#ffd971',
};

export const ROWS: string[] = [
  '                                ',
  '              Z                 ',
  '             YXZ                ',
  '            ZYXX                ',
  '           ZYXXX                ',
  '          ZYYXXX                ',
  '         ZYYXXXX                ',
  '        ZYYYXXXX                ',
  '       ZYYYYXXXXX               ',
  '       ZYYYYXXXXX               ',
  '        YYYYYXXXX               ',
  '        YYYXXXXW                ',
  '        YYXXXWWW                ',
  '         YXXWWWW                ',
  '        XYXXXXWW                ',
  '        XXXWWWWW                ',
  '         XWWWWWW                ',
  '         SWWWWWWS               ',
  '        STWWWWWTTS              ',
  '       STTWWWWWTTS              ',
  '      STTTWWWWWTTS              ',
  '     STTTTWWWWWTTTS             ',
  '    SSTTTTWWWWTTTTSS            ',
  '   SSSSTTTWWWWTTTTSSS           ',
  '  SSTCCCCCCCCCCCCTTSS           ',
  '  STCCEEEEEEEEEEECTSS           ',
  '  CCEEFFFFFFFFFFEEEDS           ',
  '  CEFFGGGGGGGGFFFEEEC           ',
  '  CFFGGHHHHGGGGFFFFEC           ',
  '  SCEFGGGGGGGGFFEECS            ',
  '   SCEFFFFGFFFFEECS             ',
  '    SCTCCCCCCCCCESS             ',
  '     SSTTTTTTTTTSSS             ',
  '      SSSSSSSSSSSS              ',
  '                                ',
  '                                ',
];